name: Deploy to development environment
on:
  push:
    branches:
    - api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Deploy
      uses: einaregilsson/beanstalk-deploy@v19
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: buskr.life
        environment_name: buskr-elb-dev
        version_label: ${{ github.SHA }}
        region: us-west-1
        deployment_package: deploy.zip
        wait_for_environment_recovery: 1000
